<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <AssemblyName>RePlayer</AssemblyName>
    <RootNamespace>RePlayer</RootNamespace>
    <Version>2.0.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.1.5" />
    <PackageReference Include="Avalonia.Desktop" Version="11.1.5" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.1.5" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.1.5" />
    <PackageReference Include="NAudio" Version="2.2.1" />
  </ItemGroup>
</Project>
